#!/usr/bin/env python3
# -*- coding: utf-8 -*-

#   Copyright 2010-2013 Tuukka Turto
#
#   This file is part of pyherc.
#
#   pyherc is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   pyherc is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with pyherc.  If not, see <http://www.gnu.org/licenses/>.

"""
Herculeum is a dungeon adventure in the spirit of Nethack and Rogue.

Usage:
  herculeum [--ui=MODE] [--log-level=LEVEL] [--silent]
  herculeum (-l | --license)
  herculeum (-h | --help)
  herculeum (-v | --version)

Options:
  -h --help            Show this screen.
  -l --license         Show license.
  -v --version         Show version.
  --ui=<mode>          User interface to use (qt or curses) [default: curses]
  --log-level=<level>  Log level to use [default: warning]
  --silent             Turns off logging completely

"""
from pyherc.aspects import set_logger
from docopt import docopt

arguments = docopt(__doc__, version='Herculeum 0.10')
set_logger(arguments['--log-level'],
           arguments['--silent'])

import sys
import os.path
import hy

from herculeum.application import Application

try:
    from herculeum.ui.gui import QtUserInterface, QtControlsConfiguration
    from herculeum.ui.gui import QtSurfaceManager
    import herculeum.ui.gui.resources
except:
    print('Qt user interface is not available')

try:
    from herculeum.ui.text import CursesUserInterface, CursesControlsConfiguration
    from herculeum.ui.text import CursesSurfaceManager
except:
    print('Curses user interface is not available')

if __name__ == "__main__":
    app = Application()    

    if arguments['--license']:
        print('#   Herculeum is free software: you can redistribute it and/or modify')
        print('#   it under the terms of the GNU General Public License as published by')
        print('#   the Free Software Foundation, either version 3 of the License, or')
        print('#   (at your option) any later version.')
        print('#')
        print('#   Herculeum is distributed in the hope that it will be useful,')
        print('#   but WITHOUT ANY WARRANTY; without even the implied warranty of')
        print('#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the')
        print('#   GNU General Public License for more details.')
        print('#')
        print('#   You should have received a copy of the GNU General Public License')
        print('#   along with Herculeum.  If not, see <http://www.gnu.org/licenses/>.')            
    else:
    
        app.process_command_line(arguments)

        if app.ui_mode == 'qt':
            user_interface = QtUserInterface(app)
            surface_manager = QtSurfaceManager()
            controls_configuration = QtControlsConfiguration()
        else:
            user_interface = CursesUserInterface(app)
            surface_manager = CursesSurfaceManager()
            controls_configuration = CursesControlsConfiguration()

        user_interface.show_splash_screen()
        app.start_logging()
        app.load_configuration(controls_configuration,
                               surface_manager)

        app.run(user_interface)
